# Dagster libraries to run both dagster-webserver and the dagster-daemon. Does not
# need to have access to any pipeline code.

FROM python:3.11-bookworm

RUN pip install \
    setuptools \
    "starlette==0.35.1" \
    dagster \
    dagster-graphql \
    dagster-webserver \
    dagster-postgres

ENV DAGSTER_HOME=/opt/dagster/dagster_home/

RUN mkdir -p $DAGSTER_HOME

COPY ./swile_dagster/dagster.yaml $DAGSTER_HOME
COPY ./swile_dagster/workspace.yaml $DAGSTER_HOME

WORKDIR $DAGSTER_HOME   
