FROM python:3.11-alpine

# Checkout and install dagster libraries needed to run the gRPC server
# exposing your repository to dagster-webserver and dagster-daemon, and to load the DagsterInstance

RUN pip install \
    setuptools \
    dagster \
    dagster-cloud \
    dagster-dbt \
    dbt-core\
    dagster-docker \
    dbt-postgres \
    sqlalchemy \
    requests \
    minio

# Add repository code

WORKDIR /opt/dagster/app

#COPY repo.py /opt/dagster/app
COPY . /opt/dagster/app
#COPY . .

WORKDIR /opt/dagster/app/swile_dagster

# Run dagster gRPC server on port 4000

EXPOSE 4000

ENV DAGSTER_DBT_PARSE_PROJECT_ON_LOAD=1

# CMD allows this to be overridden from run launchers or executors that want
# to run other commands against your repository
# CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "-f", "repo.py"]
CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000"]
# CMD ["DAGSTER_DBT_PARSE_PROJECT_ON_LOAD=1", "dagster", "dev"]
